RoomType_SizeOccupancy_guestcharge
jeiya1/HotelBilly pull request #1
Opened 2024-11-20 01:58 UTC by lourbirds

ADDED:
Input Room type 
Input Size of Occupancy
Function for Guest Charge
/*
//Let me know if there's a problem to my code or you wanna make some changes
*/

2024-11-20 11:29 UTC, jeiya1 commented
Gonna check it now.

2024-11-20 11:39 UTC, jeiya1 commented
Overall, looks good enough but expect me to make changes so it looks uniform with the rest of the code. Don't worry, you can go over the changes later and then i'll explain anything that you don't get.

2024-11-20 11:46 UTC, jeiya1 commented on src/Main.java
> +import java.lang.runtime.SwitchBootstraps;
Was this an accident? Cause this package is not supposed to be here.

2024-11-20 11:48 UTC, jeiya1 commented on src/Main.java
> +        double singleOccupancy , doubleOccupancy;
why double instead of int?

2024-11-20 11:48 UTC, jeiya1 commented on src/Main.java
> +        double userChoicePrice = 0;
why double instead of int?

2024-11-20 11:48 UTC, jeiya1 commented on src/Main.java
> +        double singleOccupancy , doubleOccupancy;
they are at a fixed price and wont contain any decimals, the only time it would contain decimals is after the computation.

2024-11-20 11:48 UTC, jeiya1 commented on src/Main.java
> +        double userChoicePrice = 0;
they are at a fixed price and wont contain any decimals, the only time it would contain decimals is after the computation.

2024-11-20 11:52 UTC, jeiya1 requested changes
- Remove the imported package
- Check your methods if it is supposed to be set as private or public
- Check your data type for userChoicePrice and Occuppancy
- Check your indentation

2024-11-20 11:52 UTC, jeiya1 commented on src/Main.java
> +    static double guestCharge(double totalBill){
Set all your methods to private, we don't need them to be accessible by other classes/programs. By default, they are public if not specified.

2024-11-20 11:52 UTC, jeiya1 commented on src/Main.java
> +    }
This has wrong indentation, remove the spaces before this closing bracket.

2024-11-23 05:47 UTC, lourbirds commented on src/Main.java
> +import java.lang.runtime.SwitchBootstraps;
yeah AHAHAH

2024-11-23 05:47 UTC, lourbirds commented on src/Main.java
> +    static double guestCharge(double totalBill){
noted

2024-11-24 09:36 UTC, lourbirds commented
I added changes, check again

2024-11-24 10:28 UTC, jeiya1 commented
> I added changes, check again
Looks good. Will merge it now.

2024-11-24 10:28 UTC, merged